name: Repo Backup

on:
  schedule:
    - cron: '0 2 * * *'   # Runs daily at 2:00 AM UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Mirror to backup remote
        env:
          BACKUP_URL: ${{ secrets.BACKUP_REPO_URL }}
        run: |
          git remote add backup "$BACKUP_URL"
          git push --mirror backup
